server:
  port: 8080

spring:
  application:
    name: redis-threadpool-learning
  
  # Redis 配置
  data:
    redis:
      host: localhost
      port: 6379
      password: 
      database: 0
      timeout: 2000
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1

# 管理端点配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,threaddump
  endpoint:
    health:
      show-details: always

# 日志配置
logging:
  level:
    root: INFO
    com.example: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/application.log

# 自定义配置
app:
  thread-pool:
    core-size: 5
    max-size: 10
    queue-capacity: 100
    keep-alive-seconds: 60
    thread-name-prefix: custom-thread-
  redis:
    key-prefix: "learning:"
    default-ttl: 3600
